### ISSUE TITLE
Texts style doesn't work on Solus

### ISSUE THREAD

**Issue by SkyzohKey** [Philip-Scott/Spice-up#128]
Hey guys,

Thanks for the awesome app (I plan to contribute to the code soon). I just spotted a very frustrating bug with texts styling (font, size, color, style).

An image is better than thousands words. I tried to apply styles with & without selecting the text, doesn't works better.

![](https://0x0.st/UPB.png)

**Comment by Philip-Scott** [comment]
Sadly, this is something that i won't be able to fix atm until elementary moves to Gtk.3.22. I'd have to maintain 2 different stylesheets to be able to support it

It could work if we could make a flatpak for Spice-Up so that it would run at Gtk.3.18 even on solus, but i don't have the time to mess with that atm. But if you or anyone else could do it that would be swell! 

I'll be closing this since it's a dup of #63 though.

**Comment by SkyzohKey** [comment]
You don't need to support 2 stylesheets, only to write your css file in a different way.

ie. for a button you can support Gtk <= 3.20 and Gtk >= 3.20 doing that;
```css
.button, button {
  background: green;
  color: white;
  font-weight: bold;
}

/**
 *  OR
 **/

GtkEntry, entry {
  border: 2px solid red;
}
```

Here's a link for reference. That's something I already done in my Ricin app (Vala too) and it worked like a charm. More code to write but at least it'll works everywhere ;)

https://developer.gnome.org/gtk3/stable/chap-css-overview.html
