### ISSUE TITLE
Set background to black in fullscreen

### ISSUE THREAD

**Issue by cassidyjames** [Philip-Scott/Spice-up#285]
If displaying a mis-matched aspect ratio (like at GUADEC!), the background of the screen is gray. Instead, it should probably be black to disappear.

```css
.fullscreen .app-back {
    background: black;
}
```
